# Generated by Django 2.2.3 on 2019-07-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('pub_date', models.DateField()),
                ('body', models.CharField(max_length=300)),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
